### ISSUE TITLE
可执行文件的相似度

### ISSUE THREAD

**Issue by CodeMasterYi** [fanghon/antiplag#4]
是否可以对可执行文件的相似度检查？

**Comment by fanghon** [comment]
抱歉，目前尚不支持对可执行文件的相似度检查。
----- 原始邮件 -----
发件人："J.M. Wu" <notifications@github.com>
收件人：fanghon/antiplag <antiplag@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[fanghon/antiplag]_可执行文件的相似度_(#4)
日期：2020年04月23日 17点05分



是否可以对可执行文件的相似度检查？



&mdash;
