### ISSUE TITLE
建议添加自定义JDK路径功能

### ISSUE THREAD

**Issue by Visors** [fanghon/antiplag#6]
我自己的Java开发环境不是JDK11，所以我设置的环境变量并非JDK11。直接运行程序会报错，但环境变量改来改去挺麻烦的，如果可以添加JDK路径自定义功能就好了。

**Comment by fanghon** [comment]
程序的启动执行就需要jdk，可以写一个 run.bat,在里面设置执行jdk11版的，然后执行
run.bat即可。
----- 原始邮件 -----
发件人：Visors <notifications@github.com>
收件人：fanghon/antiplag <antiplag@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[fanghon/antiplag]_建议添加自定义JDK路径功能_(#6)
日期：2020年05月12日 10点55分



我自己的Java开发环境不是JDK11，所以我设置的环境变量并非JDK11。直接运行程序会报错，但环境变量改来改去挺麻烦的，如果可以添加JDK路径自定义功能就好了。



&mdash;
